FROM python:3.12.7-bookworm
ENV APP_DIR=/app
WORKDIR $APP_DIR
ENV POETRY_VERSION=2.1.1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV LANG=de_DE.UTF-8
ENV LANGUAGE=de_DE:de
ENV LC_ALL=de_DE.UTF-8
RUN curl -L https://deb.nodesource.com/setup_20.x | bash - \
    && apt update -y \
    && apt install -y --no-install-recommends nodejs build-essential gettext libpq-dev locales \
    && apt autoremove -y \
    && apt clean -y \
    && rm -rf /var/lib/apt/lists/* \
    && sed -i '/de_DE.UTF-8/s/^# //g' /etc/locale.gen \
    && locale-gen \
    && update-locale LANG=de_DE.UTF-8
ENV LANG=de_DE.UTF-8
ENV LANGUAGE=de_DE:de
ENV LC_ALL=de_DE.UTF-8
COPY ../src .
RUN chmod +x /app/entrypoint.sh \
    && mkdir -p ../volume/logs \
    && touch /volume/logs/normal_handler.log \
    && touch /volume/logs/detailed_handler.log
RUN pip install --upgrade pip \
    && pip install poetry==$POETRY_VERSION
RUN poetry config virtualenvs.create false
RUN poetry self add poetry-plugin-export \
    && poetry export -f requirements.txt --without-hashes --with dev -o requirements.txt \
    && pip install -r requirements.txt
RUN npm init --init-license -y \
    && npm install tailwindcss postcss-cli autoprefixer flowbite
# ENTRYPOINT ["bash", "-e", "entrypoint.sh"]
