# Generated by Django 5.1.6 on 2025-05-31 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('content', models.TextField(max_length=500, verbose_name='Nachricht')),
                ('topic', models.IntegerField(choices=[(1, 'Ich möchte einen Fehler melden.'), (2, 'Etwas anderes'), (3, 'Ich möchte einen Verbesserungsvorschlag machen.')], default=2, verbose_name='Thema')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nutzer-Nachricht',
                'verbose_name_plural': 'Nutzer-Nachrichten',
            },
        ),
    ]
