# Generated by Django 5.1.6 on 2025-05-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reviewed_cards', models.IntegerField(default=0, verbose_name='Karten pro Tag')),
                ('initial_cards', models.IntegerField(default=0, verbose_name='Neue Karten pro Tag')),
                ('in_progress_cards', models.IntegerField(default=0, verbose_name='Wiederholte Karten pro Tag')),
                ('mastered_cards', models.IntegerField(default=0, verbose_name='Graduierte Karten pro Tag')),
                ('passed_cards', models.IntegerField(default=0, verbose_name='Richtig beantwortete Karten pro Tag')),
                ('failed_cards', models.IntegerField(default=0, verbose_name='Falsch beantwortete Karten pro Tag')),
            ],
            options={
                'verbose_name': 'Wiederholung',
                'verbose_name_plural': 'Wiederholungen',
            },
        ),
    ]
