# Generated by Django 5.1.6 on 2025-05-31 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(choices=[('A0', 'Null'), ('A1', 'Anfänger'), ('A2', 'Grundkenntnisse'), ('B1', 'Fortgeschritten'), ('B2', 'Selbständig'), ('C1', 'Fachkundig'), ('C2', 'Muttersprachennah')], max_length=2, unique=True, verbose_name='Niveaustufe')),
                ('json_file', models.FileField(blank=True, null=True, upload_to='json/', verbose_name='JSON-Datei')),
                ('slug', models.SlugField(blank=True, max_length=2)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Nutzer')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurse',
            },
        ),
    ]
